export const UNPROCCESSABLE_ENTITY_HTTP_CODE = 422;
export const DEFAULT_REQUEST_TIMEOUT = 3000;
export const DISCOVERY_SERVICE_URL = 'http://localhost:3001';
export const CONNECTION_ABORTED_HTTP_RESPONSE_CODE = 'ECONNABORTED';
